### ISSUE TITLE
Android SDK 28 now requires FOREGROUND_SERVICE permission

### ISSUE THREAD

**Issue by alexhisen** [DavidBriglio/cordova-plugin-foreground-service#10]
An app with this plugin will crash due to lack of FOREGROUND_SERVICE permission if built against Android SDK 28 (which is now required in the app store).
The plugin should add a request for this permission to the Android manifest.

You can currently work around this issue by using this plugin - https://github.com/dpa99c/cordova-custom-config and adding the following into your config.xml under `<platform name="android">`:
```
<custom-preference name="android-manifest/uses-permission/@android:name" value="android.permission.FOREGROUND_SERVICE" />
```

**Comment by wa05** [comment]
android.permission.FOREGROUND_SERVICE: java.lang.ClassNotFoundException: **Didn't find class "android.permission.FOREGROUND_SERVICE" on path: DexPathList**[[zip file "/data/app/com.mundoit.rosganet-_IV-

Why I don't have that f class ... 
Or how I install it 
I received that message after adding the permission to the config.xml ...

**Comment by alexhisen** [comment]
Make sure your config.xml also has the proper namespaces in the <widget root element, i.e.:
xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns:gap="http://phonegap.com/ns/1.0"

**Comment by wa05** [comment]
Thanks @alexhisen I think I solved updating the android api target to 29 from Visual Studio..
Maybe the class wasn't in my v28 install I don't know...

**Comment by DavidBriglio** [comment]
This has been added in version 1.1.3

**Comment by kaeverens** [comment]
for anyone else that comes across wa05's answer and is pulling their hair out trying to figure out why they're getting that exact error message, I think the Cordova build system may have some faulty caching. I had to completely rebuild my own app (remove platform, remove all plugins, clean all build artifacts, re-install plugins and platform) to get it to recompile and run on my phone. It *seems* that Cordova's caching somehow got into a state where adding a plugin (like `cordova-plugin-foreground-service`) was not also adding the `android.permission.FOREGROUND_SERVICE` class because *it believed it already had it installed*
