### ISSUE TITLE
Android 8 and higher

### ISSUE THREAD

**Issue by Elyft** [DavidBriglio/cordova-plugin-foreground-service#12]
If I understood correctly this plugin is only for users who have Android 8 and higher??

**Comment by DavidBriglio** [comment]
As outlined in the description / [Android documentation](https://developer.android.com/about/versions/oreo/background#services): this plugin creates a foreground service with a notification so that the Android OS (8+) considers your application a "foreground application". This is the only purpose of the plugin, so using it on any version below 8 would not be of any use.

This plugin alone does not guarantee background processing, so you need to use an additional background plugin for that purpose.

Let me know if you have any more questions!
