### ISSUE TITLE
BLE scan beacon for temperature

### ISSUE THREAD

**Issue by MonicaSvs** [DavidBriglio/cordova-plugin-foreground-service#21]
Hi!
I'im deploying an app ( platform Android, ionic/angular/Cordova) . In this app  i need to execute a routine every one minute to read a beacon ble  temperature.  Qhen the app goes in inactive state the BLERequestscan dont'return any value.
So i've found this plugin but i've some problem to use it.

I put the start service before my scan function and view the notification, but the scan function don't return any value.

Can you help me?

Monica

**Comment by DavidBriglio** [comment]
As outlined in the readme, you need to pair this plugin with some kind of background persisting plugin since this alone will not keep your app running in the background. Try something like this: https://github.com/katzer/cordova-plugin-background-mode. If you have any issues with my plugin please reopen this issue.
